import json
import os
import sys

# English translation of the 198 sentences.
# This data is generated by the AI to ensure high contextual accuracy.
TRANSLATIONS = {
    "Сьогодні я покажу вам, як ChatGPT можна перетворити на реальні навчальні інструменти, не просто на перекладач.": "Today I will show you how ChatGPT can be turned into real learning tools, not just a translator.",
    "І сьогодні я буду говорити не загально, а буду використовувати конкретні промти і запити, які ви також зможете відтворити.": "And today I will not speak in general terms, but I will use specific prompts and requests that you can also reproduce.",
    "Для прикладу сьогодні я буду показувати все це на рівні А1, але це відео не лише для початківців, ви зможете собі адаптувати це все також, бо ми будемо будувати прям систему навчання.": "For example, today I will show all of this at the A1 level, but this video is not only for beginners; you will be able to adapt all of this too, because we will be building a complete learning system.",
    "А в готовій промти для свого рівня ви зможете знайти у закріпленому коментарі під цим відео в моєму телеграм -каналі.": "And you can find ready-made prompts for your level in the pinned comment under this video in my Telegram channel.",
    "І наш перший крок – це база.": "And our first step is the basics.",
    "Вам потрібно достеменно знати, який рівень англійської у вас є зараз.": "You need to know exactly what level of English you have right now.",
    "Тобто не окей написати у мене щось між А2 або Б1.": "That is, it's not okay to write \"I have something between A2 or B1.\"",
    "Потрібно знати, ващий такий рівень, бо тоді ChatGPT не зможе скласти програму конкретно під вас.": "You need to know your exact level, because then ChatGPT will not be able to create a program specifically for you.",
    "Буде або щось за дуже легке, або заважке навпаки.": "It will be either too easy or, on the contrary, too difficult.",
    "На цей випадок я маю для вас готовий промт, який ви можете собі скопіювати і вставити для свого чату.": "For this case, I have a ready-made prompt for you that you can copy and paste into your chat.",
    "Зараз зачитаю.": "I'll read it now.",
    "Ти досвідчений викладач англійської мови.": "You are an experienced English teacher.",
    "Допоможи визначити мій рівень англійської.": "Help me determine my English level.",
    "Створи серію завдань, які перевіряють – лексику, грамматику, розуміння тексту, говоріння.": "Create a series of tasks that test vocabulary, grammar, reading comprehension, and speaking.",
    "Іди покроково, поступово ускладнюючи.": "Go step by step, gradually increasing the difficulty.",
    "Після моїх відповідей поясній, що це означає для мого рівня.": "After my answers, explain what this means for my level.",
    "І скажи, який він.": "And tell me what it is.",
    "І через 20 -30 хвилин у вас з 'явиться реальне розуміння, де ви зараз є і куди вам потрібно рухатись далі.": "And in 20-30 minutes, you will have a real understanding of where you are now and where you need to move next.",
    "І далі ще один критично важливий момент, яку помилку я бачу постійно, що люди відкривають дуже багато чатів і намагаються в них навчатися.": "And then another critically important point: a mistake I see constantly is that people open too many chats and try to learn in them.",
    "Але дуже важливо відкривати лише один чат і навчатися саме в ньому.": "But it is very important to open only one chat and learn specifically in that one.",
    "Тоді цей чат запам 'ятовує все про вас.": "Then this chat remembers everything about you.",
    "Які помилки ви робили, що ви не так говорили, що ви вже проходили, що потрібно ще раз закріпити.": "What mistakes you made, what you said wrong, what you've already covered, and what needs to be reinforced again.",
    "А коли ви відкриваєте нові чати, ця пам 'ять не зберігається і ви нібито заново проходите те саме.": "But when you open new chats, this memory is not preserved, and it's as if you're going through the same thing all over again.",
    "Тому фіксуємо один чат, один викладач.": "So, we stick to one chat, one teacher.",
    "Ну що ж, тепер наш другий крок.": "Well then, now for our second step.",
    "Зараз ми будемо створювати з вами того самого викладача, який буде нас навчати.": "Now we are going to create that very teacher who will be instructing us.",
    "І давайте зачитаємо цей промпт, но його зможете скопіювати потім.": "And let's read this prompt, but you can copy it later.",
    "Спочатку поясній, потім давай практику, потім повторюй, говори просто і зрозуміло.": "Explain first, then provide practice, then repeat, speak simply and clearly.",
    "І оцим кроком ви робите дуже важливу річ.": "And with this step, you are doing a very important thing.",
    "Ви не просто відкриваєте рандомний чат ще один, ви робите свого постійного стабільного викладача.": "You are not just opening another random chat; you are creating your own permanent, stable teacher.",
    "Ну от ви вже створили свого викладача, ви їм дали ціль.": "Now that you've created your teacher and given them a goal.",
    "Зараз будемо йти до практики.": "Now we're moving on to practice.",
    "Наступним кроком нам потрібно отримати від нього певні готові фрази, які відповідають нашому рівню.": "The next step is to get some ready-made phrases from them that match our level.",
    "Що ми йому пишемо?": "What do we write to them?",
    "Дай мені 10 дуже простих англійських фраз для рівня А1 на тему знайомства без граматичних пояснень.": "Give me 10 very simple English phrases for level A1 on the topic of introductions without grammar explanations.",
    "Дивіться, тут ви можете замінити і рівень, і тему, на яку ви хочете отримати ці фрази, але загалом, я думаю, логіка зрозуміла.": "You see, here you can change both the level and the topic you want to get these phrases for, but in general, I think the logic is clear.",
    "І дивіться, що він нам буде надсилати, я вам додам тут скріншот.": "And see what they will send us; I'll add a screenshot here.",
    "От він прям надсилає.": "There, they are sending it right now.",
    "Добре, ось десять дуже простих фраз для рівня А1 на тему знайомства.": "Okay, here are ten very simple phrases for level A1 on the topic of introductions.",
    "І йде перелік там, hello, hi, my name is Anna, і так далі.": "And there's a list like 'hello', 'hi', 'my name is Anna', and so on.",
    "В принципі він свою роботу зробив, він надіслав вам не просто слова, а цілі такі готові фрази.": "Basically, they've done their job; they've sent you not just words, but complete, ready-made phrases.",
    "А я думаю, що ви маєте вже знати, що гдесь кардинально потрібно вчити не окремими словами, а готовими мовними шматочками.": "And I think you should already know that it is fundamentally necessary to learn not through individual words, but through ready-made language chunks.",
    "Наступним етапом у нас буде слухання і промпт для слухання.": "The next stage will be listening, and the prompt for listening.",
    "Прочитай ці фрази в голос повільно.": "Read these phrases out loud slowly.",
    "І зараз я покажу вам, як це працює.": "And now I'll show you how it works.",
    "Звичайно.": "Certainly.",
    "Я зараз прочитаю їх чітко і повільно, щоб тобі було легко повторювати.": "I will read them clearly and slowly now, so it will be easy for you to repeat.",
    "Готовий?": "Ready?",
    "Поехали.": "Let's go.",
    "Перше.": "First.",
    "Hello.": "Hello.",
    "Друге.": "Second.",
    "Hi.": "Hi.",
    "Третє.": "Third.",
    "My name is Anna.": "My name is Anna.",
    "Шетверте.": "Fourth.",
    "I am Anna.": "I am Anna.",
    "П 'яте.": "Fifth.",
    "What is your name?": "What is your name?",
    "Шосте.": "Sixth.",
    "Nice to meet you.": "Nice to meet you.",
    "Сьоме.": "Seventh.",
    "I am from Ukraine.": "I am from Ukraine.",
    "Восме.": "Eighth.",
    "Where are you from?": "Where are you from?",
    "Дев 'яте.": "Ninth.",
    "How are you?": "How are you?",
    "Десяте.": "Tenth.",
    "I am fine.": "I am fine.",
    "Повторю.": "I'll repeat.",
    "Скільки потрібно?": "As many times as needed.",
    "Якщо треба, скажи і ми ще.": "If you need it, just say so and we'll do more.",
    "Ось так.": "Like that.",
    "Дивіться, що тут важливо.": "Look, what's important here.",
    "Ви може слухати це не один раз.": "You can listen to this more than once.",
    "Вірніше, я вам реально раджу слухати це не один раз.": "In fact, I really recommend you listen to it more than once.",
    "Для чого?": "For what purpose?",
    "Для того, щоб ви будете фіксувати собі це в голові, ваш мозок буде це краще опрацьовувати.": "So that you fix it in your head; your brain will process it better.",
    "І зможе потім це впізнавати в реальній мові, в реальній життєвій.": "And then it will be able to recognize it in real speech, in real-life situations.",
    "І також зможе потім вам підкидати варіанти цих фраз, коли ви самі будете спілкуватись англійською.": "And it will also be able to suggest options for these phrases when you are speaking English yourself.",
    "Тому слухайте як найбільше.": "So listen as much as possible.",
    "До речі, стосовно того, як це все послухати, я додам зараз ось тут таку скріншот.": "By the way, regarding how to listen to all this, I'll add a screenshot right here.",
    "На що потрібно натиснути, щоб озвучити те, що було написано.": "On what you need to click to voice over what was written.",
    "Наступним кроком у нас буде читання.": "The next step will be reading.",
    "І не якесь рандомне читання.": "And not just some random reading.",
    "А читання саме того, з чим ви щойно працювали.": "But reading specifically what you've just worked with.",
    "Тобто ми будемо ще раз відшліфовувати ті фрази і вирази, які ви і читали, і чули вже щойно.": "Meaning we will once again refine the phrases and expressions that you have both read and heard just now.",
    "І який у нас буде промпт для цього.": "And what our prompt for this will be.",
    "Дивіться.": "Look.",
    "Створим монолог історію, текст для читання.": "Create a monologue story, a text for reading.",
    "Спити шести речень для рівня А1 з цими фразами.": "Consisting of six sentences for level A1 using these phrases.",
    "Це має звучати як жива мова, один абзац, речення логічно пов 'язані, без списку і без окремих фраз, щоб можна було сказати на одному диханні.": "It should sound like natural speech, one paragraph, sentences logically connected, without lists or separate phrases, so it can be said in one breath.",
    "І зараз я вам покажу, що він мені створив.": "And now I'll show you what they created for me.",
    "Ось тут додаю такий скріншот в його відповіді.": "I'm adding a screenshot of their response here.",
    "І що робити з цим.": "And what to do with this.",
    "Ви можете прочитати це в голос собі.": "You can read it out loud to yourself.",
    "Можна не один раз навіть.": "You can even do it more than once.",
    "Можна попросити його знову це озвучити.": "You can ask them to voice it again.",
    "Через эту кнопочку, яку я вам вже показувала.": "Using this button that I already showed you.",
    "І що тут важливо, що ваш мозок сприймає те, що він десь раніше чув і він починає це пригадувати.": "And what's important here is that your brain perceives what it heard somewhere before and starts to recall it.",
    "І в цей момент ви реально навчаєтеся.": "And at that moment, you are truly learning.",
    "І от зараз ми будемо переходити до граматики.": "And now we are going to move on to grammar.",
    "Але я не буду його зараз просити, щоб він мені написав правила використання.": "But I'm not going to ask them to write usage rules for me right now.",
    "Я його попробую, щоб він мені просто це пояснив.": "I'll try to get them to just explain it to me.",
    "І дивіться, що ми можемо йому написати.": "And look at what we can write to them.",
    "Поясни.": "Explain.",
    "Дуже просто.": "Very simply.",
    "Що означає I am.": "What 'I am' means.",
    "Без граматичних термінів і складних пояснень.": "Without grammatical terms and complex explanations.",
    "Дивіться, що він мені відповідає.": "Look at how they respond to me.",
    "I am – я є.": "'I am' means 'I am'.",
    "Це те, що ти кажеш про себе.": "It's what you say about yourself.",
    "Коли ти хочеш сказати, хто ти, який ти, як ти себе почуваєш.": "When you want to say who you are, what you're like, or how you feel.",
    "Ти починаєш з I am.": "You start with 'I am'.",
    "І приклади життя далі йдуть.": "And there are life examples following.",
    "Як на мене, пояснення супер.": "In my opinion, the explanation is great.",
    "Тут немає складних термінів, тут немає якихось правил, немає часів.": "There are no complex terms here, no rules, no tenses.",
    "Просто логічно зрозуміло і на початках просто чудово.": "It's just logically clear and, for beginners, simply wonderful.",
    "Звісно, що якщо це інший якийсь рівень, то це вже буде трішки ускладнено.": "Of course, if it's a different level, it will be a bit more complicated.",
    "В промах ви це все побачите.": "You will see all of this in the prompts.",
    "Але на зараз логіка така.": "But for now, this is the logic.",
    "Ну що ж, а зараз буде мій улюблений етап.": "Well then, and now for my favorite stage.",
    "Етап, коли ми починаємо говорити з нашим чатом.": "The stage when we start talking with our chat.",
    "Знову ж таки через ось цю кнопочку.": "Again, using this button.",
    "Ми маємо перейти в режим розмови з ним.": "We have to enter the conversation mode with them.",
    "І що ми кажемо?": "And what do we say?",
    "Давай зараз з тобою зробимо простий діалогу англійською мовою для рівня A1.": "Let's have a simple dialogue in English for level A1.",
    "Ти нова для мене людина і задавай мені прості питання по черзі.": "You are a new person to me; ask me simple questions one by one.",
    "Звісно, все гаразд.": "Of course, all right.",
    "Починаємо простий діалог і я ставлю питання по черзі.": "Let's start a simple dialogue, and I'll ask questions one by one.",
    "Перше питання.": "The first question.",
    "What is your name?": "What is your name?",
    "Як тебе звати?": "What is your name?",
    "My name is Anastasia.": "My name is Anastasia.",
    "Nice to meet you, Anastasia.": "Nice to meet you, Anastasia.",
    "Where are you from?": "Where are you from?",
    "I am from Ukraine.": "I am from Ukraine.",
    "That's great.": "That's great.",
    "What do you like to do in your free time?": "What do you like to do in your free time?",
    "I like cooking and training.": "I like cooking and training.",
    "That sounds fun.": "That sounds fun.",
    "Can you tell me if you are learning English right now?": "Can you tell me if you are learning English right now?",
    "I think that you got it, that I am learning English right now.": "I think you've got it—that I am learning English right now.",
    "Absolutely.": "Absolutely.",
    "I just wanted to hear you say it.": "I just wanted to hear you say it.",
    "You are doing great.": "You are doing great.",
    "Keep it up.": "Keep it up.",
    "Ось, приблизно це відповідається якось так.": "So, it's answered roughly like this.",
    "Дивіться, якщо на якомусь етапі він щось не так буде говорити, то ви можете просто йому дати якесь уточнення стосовно цього, або ж щоб він розбивав питання по черзі, бо він інколи може видати їх прямо списком цілим.": "Look, if at some point they say something wrong, you can simply give them a clarification about it, or ask them to break down the questions one by one, because sometimes they might give them all as a whole list.",
    "Але загалом, дивіться, кльово будується розмова, ви ще можете попросити, наприклад, його перекладати кожне питання, або ж підмічати якісь ваші помилки.": "But overall, look, the conversation builds up nicely; you can also ask them, for example, to translate each question or to point out any of your mistakes.",
    "Коли ви відповідаєте, тому користуйтеся.": "When you respond, so take advantage of it.",
    "І після цього ми будемо тренувати письмо.": "And after that, we will practice writing.",
    "Так -так, вам не почулося, я завжди говорю всім.": "Yes, yes, you heard right; I always tell everyone.",
    "Чим більше ви пишете, тим краще ви говорите, тому тримайте пром для письма.": "The more you write, the better you speak, so here's the prompt for writing.",
    "Допоможи мені написати три прості речення про себе англійської для рівня, а один.": "Help me write three simple sentences about myself in English for level A1.",
    "Зараз я покажу вам, що він мені відповів, тому дивіться, додаю.": "Now I'll show you what they answered me, so look, I'm adding it.",
    "Перший він написав мені шаблони, які я можу використати.": "First, they wrote me templates that I can use.",
    "І далі він дає, типу, твій хід, тобто щоб ви йому написали ці три речення.": "And then they give you 'your move', meaning for you to write those three sentences to them.",
    "У цьому випадку, коли ви будете писати йому свої речення, він буде вас виправляти, якщо щось буде не так, або ж навпаки вас хвалити, якщо ви все написали коректно.": "In this case, when you write your sentences to them, they will correct you if something is wrong, or, on the contrary, praise you if you wrote everything correctly.",
    "І зараз дуже важливий нюанс.": "And now, a very important nuance.",
    "Після кожного заняття ви маєте зафіксувати свій прогрес.": "After each lesson, you must record your progress.",
    "Ви маєте допомогти цій машині зафіксувати все те, що йому сталося.": "You need to help this machine record everything that happened to it.",
    "Що ви йому пропишете, також пром.": "What you will write down for it is also a prompt.",
    "Зроби коротке резюме уроку, що ми пройшли, які помилки повторюються, щоб повторити наступного разу.": "Make a brief summary of the lesson: what we've covered, which mistakes are recurring, to review next time.",
    "Не більше 100 слів.": "No more than 100 words.",
    "Дивіться, ви це все можете вставити і на кінці цього уроку, і на початку наступного, для того, щоб ви справді не забували, що ви вже прийшли, і могли звертати увагу на те, на чим вам краще треба попрацювати.": "See, you can insert all of this both at the end of this lesson and at the beginning of the next one, so that you truly don't forget what you've already covered and can pay attention to what you need to work on more.",
    "А зараз буде дуже логічне запитання, певно від вас.": "And now there will be a very logical question, likely from you.",
    "Окей, я от ось сьогодні потренувалася, а що мені робити далі?": "Okay, I've practiced today, but what should I do next?",
    "Як самостійно це все робити?": "How to do all this independently?",
    "А я вам скажу, вам не потрібно вигадувати велосипед, бо я вже за вас його вигадала.": "And I'll tell you, you don't need to reinvent the wheel, because I've already reinvented it for you.",
    "Вам потрібно просто скопіювати цей промпт і далі рухатися по нашій вже створеній цій road map.": "You just need to copy this prompt and then move along our already created roadmap.",
    "Дивіться, який промпт.": "Look at the prompt.",
    "Проведи щоденний урок англійської для рівня A1.": "Conduct a daily English lesson for level A1.",
    "Один урок, один день.": "One lesson, one day.",
    "Працюй поетапно.": "Work in stages.",
    "Почни з короткого повторення того, щоб ми вже проходили.": "Start with a brief review of what we've already covered.",
    "Дві -три хвилини.": "Two or three minutes.",
    "У повторенні використовуй ті самі слова і конструкції, що і раніше.": "In the review, use the same words and structures as before.",
    "Після кожного кроку зупиняйся і чекай мого далі.": "Stop after each step and wait for my 'next'.",
    "Структура уроку.": "Lesson structure.",
    "Коротке повторення, коротке пояснення нової теми, 8 -10 простих фраз, почитай їх в голос, короткий зв 'язний текст, просте пояснення сенсу конструкцій, короткий діалог, три речення письма.": "Brief review, short explanation of a new topic, 8-10 simple phrases, read them out loud, a short coherent text, simple explanation of the meaning of constructions, a short dialogue, three sentences of writing.",
    "Говори просто і не перевантажуй.": "Speak simply and do not overload.",
    "І на цьому все.": "And that's all.",
    "Chagy Pity буде вести вас далі як реальний викладач.": "ChatGPT will lead you further like a real teacher.",
    "Це просто магія, вважаю.": "I think it's just magic.",
    "І стосовно оцих от промптів.": "And regarding these prompts.",
    "Вони написані під загальну систему навчання.": "They are written for a general learning system.",
    "Якщо вам потрібна якась конкретна тема, або конкретно розглянути якусь граматичну структуру і так далі, ви це, звісно, що можете коригувати.": "Of course, if you need a specific topic or specifically to examine a certain grammatical structure and so on, you can adjust this.",
    "Тому адаптовуйте.": "So, adapt it.",
    "Chagy Pity — це не репетитор.": "ChatGPT is not a tutor.",
    "Але з кльово вибудованою системою ви зможете створити з нього реально працюючий тренажер.": "But with a coolly built system, you can turn it into a truly working trainer.",
    "Тому тут головне — створити ось цю саму систему, щоб це було не халатично, а отак розібрано, як ми сьогодні розібрали.": "So the main thing here is to create this very system, so it's not haphazard but broken down like we did today.",
    "Бо саме так наш мозок засвої всіма пірями.": "Because that's precisely how our brain absorbs everything.",
    "Тож, якщо вам було корисно, цікаво, сподобалося, дуже буду дякую за підтримку.": "So, if it was useful, interesting, or if you liked it, I will be very grateful for your support.",
    "Ставте лайк, коментар, підписуйтесь.": "Like, comment, and subscribe.",
    "Ну, бо я це вже говорила.": "Well, because I've already said that.",
    "І хочу нагадати, що під цим відео і закріпленому коментарі ви побачите посилання на мій телеграм -канал, де будуть зібрані всі промпти для кожного рівня.": "And I want to remind you that under this video and in the pinned comment, you will see a link to my Telegram channel, where all the prompts for each level will be collected.",
    "Па-па!": "Bye-bye!",
}

def main():
    input_path = "how_fixed.json"
    output_path = "how_en.json"

    if not os.path.exists(input_path):
        print(f"Error: {input_path} not found.")
        return

    with open(input_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Translate the main text block
    if 'text' in data:
        # We could join translations, but it's easier to just map if matches exactly 
        # or leave as is if it's the whole block (though segments are more important).
        pass

    # Translate segments while keeping timestamps
    translated_count = 0
    if 'segments' in data:
        for segment in data['segments']:
            uk_text = segment.get('text', '').strip()
            if uk_text in TRANSLATIONS:
                segment['text'] = TRANSLATIONS[uk_text]
                translated_count += 1
            else:
                # Fallback: if not in map, we keep it but warn
                print(f"Warning: No translation found for: {uk_text[:50]}...")
    
    # Also update global text by joining translated segments
    data['text'] = " ".join([s['text'] for s in data.get('segments', [])])

    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Successfully saved translated transcription to {output_path}")
    print(f"Translated {translated_count} out of {len(data.get('segments', []))} segments.")

if __name__ == "__main__":
    main()
